# Generated by Django 4.0.4 on 2022-06-10 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('author_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('date_time', models.DateTimeField()),
                ('content', models.TextField()),
            ],
        ),
    ]
