# Generated by Django 4.0.4 on 2022-06-12 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='slug',
            field=models.SlugField(max_length=200, unique=True),
        ),
    ]
