# Generated by Django 4.0.4 on 2022-06-12 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_alter_comment_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='user_name',
            field=models.CharField(default='Anonymous', max_length=50),
        ),
    ]
